### ISSUE TITLE
Error: CssSyntaxError: Unexpected input if minify: true in v2.3.1

### ISSUE THREAD

**Issue by voischev** [enb/enb-borschik#49]
Обновился пакет, появилась такая ошибка при сборке. 

Css на вход подается валидный.

```
Error: CssSyntaxError: Unexpected input
Error result in /Users/voischev/projects/ui/dist/desktop/ui.min.css.borschik-error
    at /Users/voischev/projects/ui/node_modules/enb-borschik/node_modules/borschik/lib/tech.js:86:31
    at Array.<anonymous> (/Users/voischev/projects/ui/node_modules/enb-borschik/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/Users/voischev/projects/ui/node_modules/enb-borschik/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

если `minify: false` то отрабатывает норм

c `"enb-borschik": "2.3.0"` тоже нормально работает

**Comment by voischev** [comment]
Воспроизвести можно на этом проекте просто установив версию `enb-borcshik` на 2.3.1 https://github.com/alfa-bank-dev/ui

**Comment by tadatuta** [comment]
С тех пор CSSO под капотом многократно обновился. Закрываю. Если вдруг еще актуально — можно переоткрыть.
